name: ci-06

on:
  push:
    paths:
      - "06/**"
      - ".github/workflows/ci-06.yml"
  pull_request:
    paths:
      - "06/**"
      - ".github/workflows/ci-06.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "06"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run http-test-suite
        run: |
          if [ ! -f tests/http-test-suite/httptest.py ]; then
            rm -rf tests/http-test-suite
            git clone --depth 1 https://github.com/s-stupnikov/http-test-suite tests/http-test-suite
          fi
          sudo python homework/httpd.py -r homework -p 80 &
          SERVER_PID=$!
          sleep 1
          python tests/http-test-suite/httptest.py
          sudo kill $SERVER_PID
